"use client"

import { BarChart3, Building, DollarSign, Users } from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

interface DashboardOverviewProps {
  userRole?: "agent" | "company"
}

export function DashboardOverview({ userRole = "agent" }: DashboardOverviewProps) {
  const agentStats = [
    {
      title: "Active Applications",
      value: "12",
      icon: Building,
      description: "Applications in progress",
    },
    {
      title: "Accepted Opportunities",
      value: "4",
      icon: Users,
      description: "Companies you're working with",
    },
    {
      title: "Total Sales",
      value: "$24,320",
      icon: DollarSign,
      description: "Across all opportunities",
    },
    {
      title: "Retained Commissions",
      value: "$1,200",
      icon: DollarSign,
      description: "Comisiones que aún se encuentran retenidas",
    },
    {
      title: "Commissions Available",
      value: "$3,200",
      icon: DollarSign,
      description: "Comisiones que ya se encuentran disponibles",
    },
  ]

  const companyStats = [
    {
      title: "Active Opportunities",
      value: "8",
      icon: Building,
      description: "Currently open positions",
    },
    {
      title: "Total Applicants",
      value: "47",
      icon: Users,
      description: "Across all opportunities",
    },
    {
      title: "Total Sales",
      value: "$142,568",
      icon: DollarSign,
      description: "Generated by agents",
    },
    {
      title: "Growth",
      value: "+24%",
      icon: BarChart3,
      description: "Compared to last quarter",
    },
  ]

  const stats = userRole === "agent" ? agentStats : companyStats

  const cols = Math.min(stats.length, 5)


  return (
    <div className={`grid gap-5 md:grid-cols-2 lg:grid-cols-${cols}`}>
      {stats.map((stat) => (
        <Card key={stat.title}>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">{stat.title}</CardTitle>
            <stat.icon className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stat.value}</div>
            <p className="text-xs text-muted-foreground">{stat.description}</p>
          </CardContent>
        </Card>
      ))}
    </div>
  )
}
